//let initialState = [];


let initialState = [
    {
        _ID: 1,        
        CHAT_ROOM_JID: '919005835708@jewelchat.net' ,
        CREATOR_JID: '919005835708@jewelchat.net',
        SENDER_NAME: 'mayukh',
        SENDER_MSG_ID: 1,
        IS_GROUP_MSG: 0,
        MSG_TYPE:1,
        MSG_TEXT: 'Hello World',
        CREATED_DATE: '2020-01-14',
        CREATED_TIME: '16:00:00',
        JEWEL_TYPE: 3,
        IS_JEWEL_PICKED: 0,
        IS_SUBMITTED: 1,
        TIME_SUBMITTED: '',
        IS_READ: 0,
        TIME_READ: '',
        IS_DELIVERED: 0,
        TIME_DELIVERED: '',        
        IS_ERROR: 0,               
        IMAGE_BLOB: null,
        IS_IMAGE_DOWNLOADED: 0,
        IS_IMAGE_UPLOADED: 0,
        IMAGE_PATH_LOCAL: null,
        IMAGE_PATH_CLOUD: null,
        VIDEO_BLOB: null,
        IS_VIDEO_DOWNLOADED: 0,
        IS_VIDEO_UPLOADED: 0,
        VIDEO_PATH_LOCAL: null,
        VIDEO_PATH_CLOUD: null
    },
    {
        _ID: 2,        
        CHAT_ROOM_JID: '919005835708@jewelchat.net' ,
        CREATOR_JID: '919005835708@jewelchat.net',
        SENDER_NAME: 'mayukh',
        SENDER_MSG_ID: 1,
        IS_GROUP_MSG: 0,
        MSG_TYPE:1,
        MSG_TEXT: 'Hello World',
        CREATED_DATE: '2020-01-14',
        CREATED_TIME: '14:00:00',
        JEWEL_TYPE: 3,
        IS_JEWEL_PICKED: 0,
        IS_SUBMITTED: 1,
        TIME_SUBMITTED: '',
        IS_READ: 0,
        TIME_READ: '',
        IS_DELIVERED: 0,
        TIME_DELIVERED: '',        
        IS_ERROR: 0,               
        IMAGE_BLOB: null,
        IS_IMAGE_DOWNLOADED: 0,
        IS_IMAGE_UPLOADED: 0,
        IMAGE_PATH_LOCAL: null,
        IMAGE_PATH_CLOUD: null,
        VIDEO_BLOB: null,
        IS_VIDEO_DOWNLOADED: 0,
        IS_VIDEO_UPLOADED: 0,
        VIDEO_PATH_LOCAL: null,
        VIDEO_PATH_CLOUD: null
    },
    {
        _ID: 3,        
        CHAT_ROOM_JID: '919005835708@jewelchat.net' ,
        CREATOR_JID: '919005835708@jewelchat.net',
        SENDER_NAME: 'mayukh',
        SENDER_MSG_ID: 1,
        IS_GROUP_MSG: 0,
        MSG_TYPE:1,
        MSG_TEXT: 'Hello World',
        CREATED_DATE: '2020-01-14',
        CREATED_TIME: '12:00:00',
        JEWEL_TYPE: 3,
        IS_JEWEL_PICKED: 0,
        IS_SUBMITTED: 1,
        TIME_SUBMITTED: '',
        IS_READ: 0,
        TIME_READ: '',
        IS_DELIVERED: 0,
        TIME_DELIVERED: '',        
        IS_ERROR: 0,               
        IMAGE_BLOB: null,
        IS_IMAGE_DOWNLOADED: 0,
        IS_IMAGE_UPLOADED: 0,
        IMAGE_PATH_LOCAL: null,
        IMAGE_PATH_CLOUD: null,
        VIDEO_BLOB: null,
        IS_VIDEO_DOWNLOADED: 0,
        IS_VIDEO_UPLOADED: 0,
        VIDEO_PATH_LOCAL: null,
        VIDEO_PATH_CLOUD: null
    },
    {
        _ID: 4,        
        CHAT_ROOM_JID: '919005835708@jewelchat.net' ,
        CREATOR_JID: '919005835708@jewelchat.net',
        SENDER_NAME: 'mayukh',
        SENDER_MSG_ID: 1,
        IS_GROUP_MSG: 0,
        MSG_TYPE:1,
        MSG_TEXT: 'Hello World',
        CREATED_DATE: '2020-01-13',
        CREATED_TIME: '16:00:00',
        JEWEL_TYPE: 3,
        IS_JEWEL_PICKED: 0,
        IS_SUBMITTED: 1,
        TIME_SUBMITTED: '',
        IS_READ: 0,
        TIME_READ: '',
        IS_DELIVERED: 0,
        TIME_DELIVERED: '',        
        IS_ERROR: 0,               
        IMAGE_BLOB: null,
        IS_IMAGE_DOWNLOADED: 0,
        IS_IMAGE_UPLOADED: 0,
        IMAGE_PATH_LOCAL: null,
        IMAGE_PATH_CLOUD: null,
        VIDEO_BLOB: null,
        IS_VIDEO_DOWNLOADED: 0,
        IS_VIDEO_UPLOADED: 0,
        VIDEO_PATH_LOCAL: null,
        VIDEO_PATH_CLOUD: null
    },
    {
        _ID: 5,        
        CHAT_ROOM_JID: '919005835708@jewelchat.net' ,
        CREATOR_JID: '919005835708@jewelchat.net',
        SENDER_NAME: 'mayukh',
        SENDER_MSG_ID: 1,
        IS_GROUP_MSG: 0,
        MSG_TYPE:1,
        MSG_TEXT: 'Hello World',
        CREATED_DATE: '2020-01-13',
        CREATED_TIME: '14:00:00',
        JEWEL_TYPE: 3,
        IS_JEWEL_PICKED: 0,
        IS_SUBMITTED: 1,
        TIME_SUBMITTED: '',
        IS_READ: 0,
        TIME_READ: '',
        IS_DELIVERED: 0,
        TIME_DELIVERED: '',        
        IS_ERROR: 0,               
        IMAGE_BLOB: null,
        IS_IMAGE_DOWNLOADED: 0,
        IS_IMAGE_UPLOADED: 0,
        IMAGE_PATH_LOCAL: null,
        IMAGE_PATH_CLOUD: null,
        VIDEO_BLOB: null,
        IS_VIDEO_DOWNLOADED: 0,
        IS_VIDEO_UPLOADED: 0,
        VIDEO_PATH_LOCAL: null,
        VIDEO_PATH_CLOUD: null
    },
    {
        _ID: 6,        
        CHAT_ROOM_JID: '919005835708@jewelchat.net' ,
        CREATOR_JID: '919005835708@jewelchat.net',
        SENDER_NAME: 'mayukh',
        SENDER_MSG_ID: 1,
        IS_GROUP_MSG: 0,
        MSG_TYPE:1,
        MSG_TEXT: 'Hello World',
        CREATED_DATE: '2020-01-13',
        CREATED_TIME: '12:00:00',
        JEWEL_TYPE: 3,
        IS_JEWEL_PICKED: 0,
        IS_SUBMITTED: 1,
        TIME_SUBMITTED: '',
        IS_READ: 0,
        TIME_READ: '',
        IS_DELIVERED: 0,
        TIME_DELIVERED: '',        
        IS_ERROR: 0,               
        IMAGE_BLOB: null,
        IS_IMAGE_DOWNLOADED: 0,
        IS_IMAGE_UPLOADED: 0,
        IMAGE_PATH_LOCAL: null,
        IMAGE_PATH_CLOUD: null,
        VIDEO_BLOB: null,
        IS_VIDEO_DOWNLOADED: 0,
        IS_VIDEO_UPLOADED: 0,
        VIDEO_PATH_LOCAL: null,
        VIDEO_PATH_CLOUD: null
    },
    {
        _ID: 7,        
        CHAT_ROOM_JID: '919005835708@jewelchat.net' ,
        CREATOR_JID: '919005835709@jewelchat.net',
        SENDER_NAME: 'mayukh',
        SENDER_MSG_ID: 1,
        IS_GROUP_MSG: 0,
        MSG_TYPE:1,
        MSG_TEXT: 'Hello World',
        CREATED_DATE: '2020-01-13',
        CREATED_TIME: '10:00:00',
        JEWEL_TYPE: 3,
        IS_JEWEL_PICKED: 0,
        IS_SUBMITTED: 1,
        TIME_SUBMITTED: '',
        IS_READ: 0,
        TIME_READ: '',
        IS_DELIVERED: 0,
        TIME_DELIVERED: '',        
        IS_ERROR: 0,               
        IMAGE_BLOB: null,
        IS_IMAGE_DOWNLOADED: 0,
        IS_IMAGE_UPLOADED: 0,
        IMAGE_PATH_LOCAL: null,
        IMAGE_PATH_CLOUD: null,
        VIDEO_BLOB: null,
        IS_VIDEO_DOWNLOADED: 0,
        IS_VIDEO_UPLOADED: 0,
        VIDEO_PATH_LOCAL: null,
        VIDEO_PATH_CLOUD: null
    },
    {
        _ID: 8,        
        CHAT_ROOM_JID: '919005835708@jewelchat.net' ,
        CREATOR_JID: '919005835708@jewelchat.net',
        SENDER_NAME: 'mayukh',
        SENDER_MSG_ID: 1,
        IS_GROUP_MSG: 0,
        MSG_TYPE:1,
        MSG_TEXT: 'Hello World',
        CREATED_DATE: '2020-01-12',
        CREATED_TIME: '12:00:00',
        JEWEL_TYPE: 3,
        IS_JEWEL_PICKED: 0,
        IS_SUBMITTED: 1,
        TIME_SUBMITTED: '',
        IS_READ: 0,
        TIME_READ: '',
        IS_DELIVERED: 0,
        TIME_DELIVERED: '',        
        IS_ERROR: 0,               
        IMAGE_BLOB: null,
        IS_IMAGE_DOWNLOADED: 0,
        IS_IMAGE_UPLOADED: 0,
        IMAGE_PATH_LOCAL: null,
        IMAGE_PATH_CLOUD: null,
        VIDEO_BLOB: null,
        IS_VIDEO_DOWNLOADED: 0,
        IS_VIDEO_UPLOADED: 0,
        VIDEO_PATH_LOCAL: null,
        VIDEO_PATH_CLOUD: null
    },
    {
        _ID: 9,        
        CHAT_ROOM_JID: '919005835708@jewelchat.net' ,
        CREATOR_JID: '919005835708@jewelchat.net',
        SENDER_NAME: 'mayukh',
        SENDER_MSG_ID: 1,
        IS_GROUP_MSG: 0,
        MSG_TYPE:1,
        MSG_TEXT:  'Hello World Well organized and easy to understand Web building tutorials with lots of examples',
        CREATED_DATE: '2020-01-12',
        CREATED_TIME: '10:00:00',
        JEWEL_TYPE: 3,
        IS_JEWEL_PICKED: 0,
        IS_SUBMITTED: 1,
        TIME_SUBMITTED: '',
        IS_READ: 0,
        TIME_READ: '',
        IS_DELIVERED: 0,
        TIME_DELIVERED: '',        
        IS_ERROR: 0,               
        IMAGE_BLOB: null,
        IS_IMAGE_DOWNLOADED: 0,
        IS_IMAGE_UPLOADED: 0,
        IMAGE_PATH_LOCAL: null,
        IMAGE_PATH_CLOUD: null,
        VIDEO_BLOB: null,
        IS_VIDEO_DOWNLOADED: 0,
        IS_VIDEO_UPLOADED: 0,
        VIDEO_PATH_LOCAL: null,
        VIDEO_PATH_CLOUD: null
    },
    {
        _ID: 10,        
        CHAT_ROOM_JID: '919005835708@jewelchat.net' ,
        CREATOR_JID: '919005835709@jewelchat.net',
        SENDER_NAME: 'mayukh',
        SENDER_MSG_ID: 1,
        IS_GROUP_MSG: 0,
        MSG_TYPE:1,
        MSG_TEXT: 'Hello World ',
        CREATED_DATE: '2020-01-12',
        CREATED_TIME: '08:00:00',
        JEWEL_TYPE: 3,
        IS_JEWEL_PICKED: 0,
        IS_SUBMITTED: 1,
        TIME_SUBMITTED: '',
        IS_READ: 0,
        TIME_READ: '',
        IS_DELIVERED: 0,
        TIME_DELIVERED: '',        
        IS_ERROR: 0,               
        IMAGE_BLOB: null,
        IS_IMAGE_DOWNLOADED: 0,
        IS_IMAGE_UPLOADED: 0,
        IMAGE_PATH_LOCAL: null,
        IMAGE_PATH_CLOUD: null,
        VIDEO_BLOB: null,
        IS_VIDEO_DOWNLOADED: 0,
        IS_VIDEO_UPLOADED: 0,
        VIDEO_PATH_LOCAL: null,
        VIDEO_PATH_CLOUD: null
    }
    


]
    
    
    

        
const chatroom = (state = initialState, action) => {
    switch (action.type) {
             
        default:            
            return state      
              
    }
}

export default chatroom